---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-merge-conflict
    exclude: rst$
- repo: https://github.com/asottile/yesqa
  rev: v1.4.0
  hooks:
  - id: yesqa
- repo: https://github.com/Zac-HD/shed
  rev: 0.10.7
  hooks:
  - id: shed
    args:
    - --refactor
    types_or:
    - python
    - markdown
    - rst
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.2.2
  hooks:
  - id: yamlfmt
    args: [--mapping, '2', --sequence, '2', --offset, '0']
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: fix-encoding-pragma
    args: [--remove]
  - id: check-case-conflict
  - id: check-json
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
- repo: https://github.com/pycqa/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
    language_version: python3
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.9.0
  hooks:
  - id: python-use-type-annotations
- repo: https://github.com/rhysd/actionlint
  rev: v1.6.22
  hooks:
  - id: actionlint-docker
    args:
    - -ignore
    - 'SC2155:'
    - -ignore
    - 'SC2086:'
    - -ignore
    - 'SC1004:'
- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.19.2
  hooks:
  - id: check-github-actions
ci:
  skip:
  - actionlint-docker
  - check-github-actions
